services:
  iac_website:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: iac_website
    ports:
    - 5000:80
    hostname: iac_website
    container_name: iac_website
